
title: Luu Tuan Anh
url: 'http://rockkhuya.com'


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Luu Tuan Anh
tagline: ルー　トアン　アン
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: rock.khuya@gmail.com
phone: (+84) 0934 898 137
website: vietonrails.com #do not add http://
github: rockkhuya

#Update all the sections by editing the files inside _includes folder.
